// Greenhouse public board slugs. Each appears at boards.greenhouse.io/{slug}.
export const GREENHOUSE_COMPANIES: { slug: string; name: string }[] = [
  { slug: 'airbnb', name: 'Airbnb' },
  { slug: 'stripe', name: 'Stripe' },
  { slug: 'anthropic', name: 'Anthropic' },
  { slug: 'openai', name: 'OpenAI' },
  { slug: 'vercel', name: 'Vercel' },
  { slug: 'supabase', name: 'Supabase' },
  { slug: 'ramp', name: 'Ramp' },
  { slug: 'mercury', name: 'Mercury' },
  { slug: 'retool', name: 'Retool' },
  { slug: 'linear', name: 'Linear' },
  { slug: 'notion', name: 'Notion' },
  { slug: 'discord', name: 'Discord' },
  { slug: 'figma', name: 'Figma' },
  { slug: 'doordash', name: 'DoorDash' },
  { slug: 'plaid', name: 'Plaid' },
  { slug: 'brex', name: 'Brex' },
  { slug: 'chime', name: 'Chime' },
  { slug: 'robinhood', name: 'Robinhood' },
  { slug: 'gusto', name: 'Gusto' },
  { slug: 'zapier', name: 'Zapier' },
  { slug: 'asana', name: 'Asana' },
  { slug: 'dropbox', name: 'Dropbox' },
  { slug: 'gitlab', name: 'GitLab' },
  { slug: 'hashicorp', name: 'HashiCorp' },
  { slug: 'datadog', name: 'Datadog' },
  { slug: 'snowflake', name: 'Snowflake' },
  { slug: 'databricks', name: 'Databricks' },
  { slug: 'scaleai', name: 'Scale AI' },
  { slug: 'glean', name: 'Glean' },
  { slug: 'perplexityai', name: 'Perplexity' },
];
