import Link from 'next/link';

export const metadata = {
  title: 'Terms — Job Cannon',
};

function H2({ children }: { children: React.ReactNode }) {
  return (
    <h2 className="font-display text-2xl tracking-tight mt-12 mb-4">{children}</h2>
  );
}

function P({ children }: { children: React.ReactNode }) {
  return (
    <p className="text-[0.9375rem] leading-relaxed text-foreground/85 mt-4">{children}</p>
  );
}

function Bullet({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <li className="mt-4 grid gap-1 sm:grid-cols-[10rem_1fr]">
      <span className="text-[0.6875rem] uppercase tracking-wider text-muted-foreground">
        {label}
      </span>
      <span className="text-[0.9375rem] leading-relaxed text-foreground/85">{children}</span>
    </li>
  );
}

export default function TermsPage() {
  return (
    <main className="mx-auto w-full max-w-3xl px-4 py-16 sm:px-6 sm:py-24">
      <p className="text-[0.6875rem] uppercase tracking-wider text-muted-foreground">
        Last updated · 2026-05-22
      </p>
      <h1 className="mt-3 font-display text-5xl tracking-tight">Terms.</h1>

      <H2>The service</H2>
      <P>
        Job Cannon ranks publicly listed startup job postings against the resume you upload. Job
        postings are scraped from public APIs (Greenhouse, Lever, RemoteOK). Match scores and
        reasoning are generated by Anthropic&apos;s Claude API based on your resume. None of this
        guarantees a job, an interview, or a fit — we&apos;re a ranking tool, not a recruiter.
      </P>

      <H2>Subscriptions</H2>
      <P>
        Paid plans bill monthly ($8) or annually ($60) via Stripe. Every plan starts with a 7-day
        free trial. Cancel any time before the trial ends and you won&apos;t be charged. After the
        trial, you can cancel mid-period via the billing portal; access continues until the end of
        the current period and no further charges occur.
      </P>

      <H2>Acceptable use</H2>
      <ul className="border-b border-border">
        <Bullet label="Your resume">
          Upload only resumes belonging to you. Don&apos;t upload material you don&apos;t have rights to.
        </Bullet>
        <Bullet label="No scraping">
          Don&apos;t use the service to scrape, redistribute, or republish job postings.
        </Bullet>
        <Bullet label="Rate limits">Don&apos;t abuse the upload endpoint.</Bullet>
      </ul>

      <H2>Liability</H2>
      <P>
        The service is provided as-is. We&apos;re not liable for missed opportunities, employer
        decisions, scraping coverage gaps, or any consequential damage from using the rankings.
      </P>

      <H2>Changes</H2>
      <P>
        We&apos;ll update these terms when we change pricing, features, or policies. Material
        changes will be communicated by email to active subscribers.
      </P>

      <H2>Contact</H2>
      <P>
        File issues at{' '}
        <Link
          href="https://github.com/abdelrahmanebensahla/job-cannon"
          className="text-foreground underline underline-offset-2"
        >
          github.com/abdelrahmanebensahla/job-cannon ↗
        </Link>
        .
      </P>
    </main>
  );
}
