export const metadata = {
  title: 'Terms of service — Job Cannon',
};

export default function TermsPage() {
  return (
    <main className="mx-auto w-full max-w-3xl px-4 py-10 sm:px-6 sm:py-16">
      <article className="prose prose-sm dark:prose-invert max-w-none">
        <h1>Terms of service</h1>
        <p>
          <em>Last updated: 2026-05-22.</em>
        </p>

        <h2>The service</h2>
        <p>
          Job Cannon ranks publicly listed startup job postings against the resume you upload. Job
          postings are scraped from public APIs (Greenhouse, Lever, RemoteOK). Match scores and
          reasoning are generated by Anthropic&apos;s Claude API based on your resume. None of this
          guarantees a job, an interview, or a fit — we&apos;re a ranking tool, not a recruiter.
        </p>

        <h2>Subscriptions</h2>
        <p>
          Paid plans bill monthly ($9) or annually ($80) via Stripe. Every plan starts with a 7-day
          free trial. Cancel any time before the trial ends and you won&apos;t be charged. After the
          trial, you can cancel mid-period via the billing portal; access continues until the end
          of the current period and no further charges occur.
        </p>

        <h2>Acceptable use</h2>
        <ul>
          <li>Upload only resumes belonging to you. Don&apos;t upload material you don&apos;t have rights to.</li>
          <li>Don&apos;t use the service to scrape, redistribute, or republish job postings.</li>
          <li>Don&apos;t abuse the upload endpoint (rate limits apply).</li>
        </ul>

        <h2>Liability</h2>
        <p>
          The service is provided as-is. We&apos;re not liable for missed opportunities, employer
          decisions, scraping coverage gaps, or any consequential damage from using the rankings.
        </p>

        <h2>Changes</h2>
        <p>
          We&apos;ll update these terms when we change pricing, features, or policies. Material changes
          will be communicated by email to active subscribers.
        </p>

        <h2>Contact</h2>
        <p>
          File issues at{' '}
          <a href="https://github.com/abdelrahmanebensahla/job-cannon">
            github.com/abdelrahmanebensahla/job-cannon
          </a>
          .
        </p>
      </article>
    </main>
  );
}
